from exceptions.telegram_exception import TelegramException


class Conflict(TelegramException):
    pass
